config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post 'authenticate', to: 'authentication#authenticate'
      resources :articles, only: [:index]
    end
  end

  resources :novels

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :articles,concerns: :paginatable

  root "articles#index"

  mount Sidekiq::Web => '/sikekiq'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/novel.rb
class Novel < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workflow_db.rb
class WorkflowDb < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: {writing: :workflow }
  #establish_connection :workflow
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API

    before_action :authenticate_request
    attr_reader :current_api_user


    private
    #如果header中 Authorization 验证通过，即会返回该用户
    #headers['Authorization']中的格式为 {user_id: xx, exp:xxx}
    def authenticate_request
      command = AuthorizeApiRequest.call(request.headers)
      Rails.logger.debug "-----------"
      Rails.logger.debug command.errors

      @current_api_user = command.result

      render json: {error: command.errors.full_messages }, status: :unauthorized unless command.success?
    end

  end


end

app/controllers/api/v1/articles_controller.rb
module Api
  module V1
    class ArticlesController < Api::ApplicationController
      def index
        articles = Article.page(params[:page]).per(10)
        articles = articles.map do |art|
          {id: art.id, title: art.title}
        end
        render json: {results: articles, cur_page: params[:page] || 1}, status: :ok
      end

    end
  end
end

app/controllers/api/v1/authentication_controller.rb
module Api
  module V1
    class AuthenticationController < Api::ApplicationController
      skip_before_action :authenticate_request

      def authenticate
        command = AuthenticateUser.call(params[:email], params[:password])

        if command.success?
          render json: {authen_token: command.result}
        else
          render json: {error: command.errors}, status: :unauthorized
        end

      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.page(params[:page]).per(2)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :set_novel, only: [:show, :edit, :update, :destroy]

  # GET /novels
  # GET /novels.json
  def index
    @novels = Novel.all
  end

  # GET /novels/1
  # GET /novels/1.json
  def show
  end

  # GET /novels/new
  def new
    @novel = Novel.new
  end

  # GET /novels/1/edit
  def edit
  end

  # POST /novels
  # POST /novels.json
  def create
    @novel = Novel.new(novel_params)

    respond_to do |format|
      if @novel.save
        format.html { redirect_to @novel, notice: 'Novel was successfully created.' }
        format.json { render :show, status: :created, location: @novel }
      else
        format.html { render :new }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novels/1
  # PATCH/PUT /novels/1.json
  def update
    respond_to do |format|
      if @novel.update(novel_params)
        format.html { redirect_to @novel, notice: 'Novel was successfully updated.' }
        format.json { render :show, status: :ok, location: @novel }
      else
        format.html { render :edit }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novels/1
  # DELETE /novels/1.json
  def destroy
    @novel.destroy
    respond_to do |format|
      format.html { redirect_to novels_url, notice: 'Novel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novel
      @novel = Novel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def novel_params
      params.require(:novel).permit(:title, :author, :ccontent)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= page_entries_info @articles, entry_name: "item" %>
<%= paginate @articles %>
<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/novels/_form.html.erb
<%= form_with(model: novel) do |form| %>
  <% if novel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(novel.errors.count, "error") %> prohibited this novel from being saved:</h2>

      <ul>
        <% novel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :ccontent %>
    <%= form.text_field :ccontent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/novels/edit.html.erb
<h1>Editing Novel</h1>

<%= render 'form', novel: @novel %>

<%= link_to 'Show', @novel %> |
<%= link_to 'Back', novels_path %>

app/views/novels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Novels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Ccontent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @novels.each do |novel| %>
      <tr>
        <td><%= novel.title %></td>
        <td><%= novel.author %></td>
        <td><%= novel.ccontent %></td>
        <td><%= link_to 'Show', novel %></td>
        <td><%= link_to 'Edit', edit_novel_path(novel) %></td>
        <td><%= link_to 'Destroy', novel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Novel', new_novel_path %>

app/views/novels/new.html.erb
<h1>New Novel</h1>

<%= render 'form', novel: @novel %>

<%= link_to 'Back', novels_path %>

app/views/novels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @novel.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @novel.author %>
</p>

<p>
  <strong>Ccontent:</strong>
  <%= @novel.ccontent %>
</p>

<%= link_to 'Edit', edit_novel_path(@novel) %> |
<%= link_to 'Back', novels_path %>